### ISSUE TITLE
Small Things

### ISSUE THREAD

**Issue by acbart** [Miles-Simpson/CISC367_Intro#1]
Hello, this looks like a good start.

I'd like you to make sure you don't commit your `lib/site-packages` folder or any of the other system folders that you included. In general, you should have a [`gitignore` file](https://medium.com/@cruble/a-quick-guide-for-making-a-git-ignore-gitignore-e645d70676b2) to avoid committing stuff like that. 

Leave a comment here when you've cleaned up the repo and I'll go fix the grade!

**Comment by Miles-Simpson** [comment]
Should be cleaned up now.

**Comment by acbart** [comment]
Agreed - looks good! I'll go fix things on canvas.
